export const popup: string;
export const icon: string;
export const error: string;
export const warning: string;
export const success: string;
export const none: string;
export const title: string;
export const subtitle: string;
export const buttons: string;
